name: Issue report
description: Report issues
labels: ["Awaiting triage"]
assignees: self

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue!
        * Before reporting a new issue please check and search in [List of existing issues](https://github.com/Erriez/midi-sysex-io/issues?q=is%3Aissue) 
        * Please check [Online Documentation](https://github.com/Erriez/midi-sysex-io/blob/master/README.md)

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of this repository is used? Please consider to update to the latest version when possible.
      options:
        - master
        - v1.0.0
        - other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your problem here and expected behaviour.
      placeholder: ex. Build error, weird or wrong behaviour, etc..
    validations:
      required: true

  - type: textarea
    id: testcase
    attributes:
      label: Testcase
      description: Please describe exact steps to reproduce your problem.
      placeholder: ex. 1. Build example XYZ, 2. Run on the board, 3. Send message..., etc
    validations:
      required: true

  - type: textarea
    id: sketch
    attributes:
      label: Sketch
      description: Please provide code which can be run to reproduce your issue.
      placeholder: ex. Related part of the code to replicate the issue
      render: cpp
    validations:
     required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please provide a logs or error message.
      placeholder: When possible, enable QT_DEBUG_PLUGINS=1 and show Nuitka build output here.
      render: plain
    validations:
      required: true 

  - type: checkboxes
    id: confirmation
    attributes:
      label: Checks
      description: You agree to check all the resources above before opening a new issue.
      options:
        - label: I confirm I have checked existing issues, online documentation and latest version when possible.
          required: true
      options:
        - label: I understand that this repository is maintained by volunteers in spare time. Response time may vary.
          required: true
          
  - type: checkboxes
    id: restrictions
    attributes:
      label: Export restrictions.
      description: The owner of this repository Erriez included an explict export restriction to Russia.
      options:
        - label: I accept [End User Agreement](https://github.com/Erriez/midi-sysex-io/blob/master/END_USER_AGREEMENT.md).
          required: true

  - type: markdown
    attributes:
      value: Thanks for your contribution!
